[package]
name = "asciiframe"
version = "0.6.0"
categories = ["command-line-utilities"]
description = "Watch any video in the terminal with ASCII"
homepage = "https://github.com/ltgr/asciiframe"
authors = ["Luke"]
license = "MIT"
edition = "2021"

[[bin]]
name = "asc"
path = "src/main.rs"

[dependencies]
clap = { version = "3.0.4", features = ["derive", "cargo"] }
opencv = "0.61"
colored = "2"
termsize = "0.1.6"
faccess = "0.2.3"
