[package]
name = "asciiframe"
authors = ["Luke"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.0", features = ["derive", "cargo"] }
opencv = "0.61"
colored = "2"
termsize = "0.1.6"
faccess = "0.2.3"
