[package]
name = "asciiframe"
version = "0.1.4"
keywords = ["cli", "ascii", "opencv"]
categories = ["command-line-utilities"]
description = "Watch any video in the terminal with ASCII"
homepage = "https://github.com/ltgr/asciiframe"
authors = ["Luke"]
license = "MIT"
edition = "2021"
exclude = ["ci/benchmarks/*"]

[[bin]]
name = "asc"
path = "src/main.rs"

[dependencies]
clap = { version = "3.0.7", features = ["derive", "cargo"] }
opencv = "0.62"
indicatif = "0.16.2"
terminal_size = "0.1.17"
ansi_term = "0.12.1"
# ansi_colours = "^1.0"
