name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  src:
    strategy:
      matrix:
        os:
          - image: ubuntu-latest
          - image: macos-latest
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dependencies
        run: ci/deps.sh
        shell: bash

      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          default: true
          toolchain: nightly

      - name: Build project
        run: ci/build.sh
        shell: bash
