name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dependencies
      run: sudo sh -c /ci/deps-debian.sh

    - name: Rust Toolchain
      uses: actions-rs/toolchain@v1

    - name: Build
      run: cargo build --verbose
