name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dependencies
      run: sudo apt-get install clang libclang-dev

    - name: OpenCV Installation
      uses: Dovyski/setup-opencv-action@v1

    - name: Rust Toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: nightly

    - name: Build
      run: cargo build --verbose

  darwin:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dependencies
      run: |
        export DYLD_FALLBACK_LIBRARY_PATH="$(xcode-select --print-path)/usr/lib/"
        brew install llvm
        brew install opencv

    - name: Rust Toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: nightly

    - name: Build
      run: cargo build --verbose

